name: CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.4.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic App
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android
        
      - name: Build Android Dev APK
        run: ionic capacitor build android
        
      - name: Build Android Release APK
        run: ionic capacitor build android --release --prod
        
      - name: Grant execute permission for publishing script
        working-directory: ./android/
        run: chmod +x ./gradlew
               
      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundleRelease
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0        
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0        
        with:
          name: app-dev
          path: my-wallet/android/app/build/outputs/apk/debug/app-debug.apk
          
      - name: Upload release bundleRelease
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-release
          path: platforms/android/app/build/outputs/bundle/release/app-debug.apk
          
      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: apk/app-debug.apk
